import kbIndexJson from "./kb_index.json";

export interface KbEntry {
  id: string;
  crop: string;
  name_en: string;
  ai_hint_en: string;
}

interface KbIndexFile {
  schema: number;
  version: string;
  seq: number;
  entries: KbEntry[];
}

/** Candidate list for the classifier prompt, generated by tools/kb_build (never hand-edited). */
export class KbIndex {
  constructor(private readonly data: KbIndexFile) {}

  get seq(): number {
    return this.data.seq;
  }
  get version(): string {
    return this.data.version;
  }
  hasCrop(crop: string): boolean {
    return this.data.entries.some((e) => e.crop === crop);
  }
  forCrop(crop: string): KbEntry[] {
    return this.data.entries.filter((e) => e.crop === crop);
  }
  has(id: string): boolean {
    return this.data.entries.some((e) => e.id === id);
  }
  isValid(crop: string, diseaseId: string): boolean {
    return this.data.entries.some((e) => e.crop === crop && e.id === diseaseId);
  }
}

let cached: KbIndex | undefined;

export function loadKbIndex(): KbIndex {
  return (cached ??= new KbIndex(kbIndexJson as KbIndexFile));
}
